# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

  # Manually triggered from the Actions tab
  workflow_dispatch:
  
  # Runs on every push to the 'main' branch
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Generate Snake Animation using Platane's action
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the newly generated files to the 'output' branch
      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionally, run a status check on the repository
      - name: Show repository status
        run: git status
        continue-on-error: true
